Build updates from Jay

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,7 +9,6 @@ defaults:
     working-directory: src
 
 env:
-  GAMVERSION: 6.68.04
   OPENSSL_CONFIG_OPTS: no-fips --api=3.0.0
   OPENSSL_INSTALL_PATH: ${{ github.workspace }}/bin/ssl
   OPENSSL_SOURCE_PATH: ${{ github.workspace }}/src/openssl
@@ -33,17 +32,17 @@ jobs:
             jid: 2
             goal: build
             arch: x86_64
-            openssl_archs: darwin64-x86_64 darwin64-arm64
-          - os: macos-12
+            openssl_archs: darwin64-x86_64
+          - os: macos-14
             jid: 3
             goal: build
             arch: arm64
+            openssl_archs: darwin64-arm64
+          - os: macos-14
+            jid: 4
+            goal: build
+            arch: universal2
             openssl_archs: darwin64-x86_64 darwin64-arm64
-          # - os: macos-12
-          #   jid: 4
-          #   goal: build
-          #   arch: universal2
-          #   openssl_archs: darwin64-x86_64 darwin64-arm64
           - os: windows-2022
             jid: 5
             goal: build
@@ -68,15 +67,14 @@ jobs:
         id: cache-python-ssl
         with:
           path: |
-            bin.tar.xz
-            src/cpython
-          key: gam-${{ matrix.jid }}-20240208
+            cache.tar.xz
+          key: gam-${{ matrix.jid }}-20240209
 
       - name: Untar Cache archive
         if: matrix.goal == 'build' && steps.cache-python-ssl.outputs.cache-hit == 'true'
         working-directory: ${{ github.workspace }}
         run: |
-          tar xvvf bin.tar.xz
+          tar xvvf cache.tar.xz
 
       - name: Use pre-compiled Python for testing
         if: matrix.python != ''
@@ -125,8 +123,9 @@ jobs:
           curl $curl_retry -fsS -o rust.sh https://sh.rustup.rs
           bash ./rust.sh -y
           source $HOME/.cargo/env
-          # needed for Rust to compile cryptography Python package for universal2
-          rustup target add aarch64-apple-darwin
+          # Install needed packages
+          brew update
+          brew install gpg swig
 
       - name: Windows Configure VCode
         uses: ilammy/msvc-dev-cmd@v1
@@ -156,14 +155,11 @@ jobs:
             CHOC_OPS="--forcex86"
           fi
           if [[ "${RUNNER_OS}" == "macOS" ]]; then
-            #brew install coreutils
-            #brew install bash
             MAKE=make
             MAKEOPT="-j$(sysctl -n hw.logicalcpu)"
             PERL=perl
             echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV
             echo "PYTHON=${PYTHON_INSTALL_PATH}/bin/python3" >> $GITHUB_ENV
-            #echo "PIP_ARGS=--no-binary=:all:" >> $GITHUB_ENV
           elif [[ "${RUNNER_OS}" == "Linux" ]]; then
             MAKE=make
             MAKEOPT="-j$(nproc)"
@@ -200,7 +196,7 @@ jobs:
           git checkout "${LATEST_STABLE_TAG}"
           export COMPILED_OPENSSL_VERSION=${LATEST_STABLE_TAG:8} # Trim the openssl- prefix
           echo "COMPILED_OPENSSL_VERSION=${COMPILED_OPENSSL_VERSION}" >> $GITHUB_ENV
-          if [[ "${RUNNER_OS}" == "macOS" ]]; then
+          if ([ "${RUNNER_OS}" == "macOS" ] && [ "$arch" == "universal2" ]); then
             for openssl_arch in $openssl_archs; do
               ssldir="${OPENSSL_SOURCE_PATH}-${openssl_arch}"
               mkdir -v "${ssldir}"
@@ -240,7 +236,7 @@ jobs:
       - name: Install OpenSSL
         if: matrix.goal == 'build' && steps.cache-python-ssl.outputs.cache-hit != 'true'
         run: |
-          if [[ "${RUNNER_OS}" == "macOS" ]]; then
+          if ([ "${RUNNER_OS}" == "macOS" ] && [ "$arch" == "universal2" ]); then
             for openssl_arch in $openssl_archs; do
               cd "${GITHUB_WORKSPACE}/src/openssl-${openssl_arch}"
               # install_sw saves us ages processing man pages :-)
@@ -292,7 +288,7 @@ jobs:
         if: matrix.goal == 'build' && runner.os != 'Windows' && steps.cache-python-ssl.outputs.cache-hit != 'true'
         run: |
           cd "${PYTHON_SOURCE_PATH}"
-          if [[ "${RUNNER_OS}" == "macOS" ]]; then
+          if ([ "${RUNNER_OS}" == "macOS" ] && [ "$arch" == "universal2" ]); then
             extra_args=( "--enable-universalsdk" "--with-universal-archs=universal2" )
           else
             extra_args=( )
@@ -383,40 +379,26 @@ jobs:
         run: |
           echo "before anything..."
           "${PYTHON}" -m pip list
-          if [[ "${RUNNER_OS}" == "macOS" ]]; then
-            if [[ "${arch}" == "arm64" ]]; then
-              # export CFLAGS="-arch arm64"
-              # export ARCHFLAGS="-arch arm64"
-              # CFFI_PLATFORM="macosx_11_0_arm64"
-              CRYPT_PLATFORM="macosx_11_0_arm64"
-              export CFLAGS="-arch x86_64 -arch arm64"
-              export ARCHFLAGS="-arch x86_64 -arch arm64"
-              CRYPT_PLATFORM="macosx_10_15_universal2"
-            elif [[ "${arch}" == "x86_64" ]]; then
-              export CFLAGS="-arch x86_64"
-              export ARCHFLAGS="-arch x86_64"
-              # CFFI_PLATFORM="macosx_10_9_x86_64"
-              CRYPT_PLATFORM="macosx_10_15_x86_64"
-            else
-              export CFLAGS="-arch x86_64 -arch arm64"
-              export ARCHFLAGS="-arch x86_64 -arch arm64"
-              CRYPT_PLATFORM="macosx_10_15_universal2"
-            fi
-            echo "before cffi..."
+          if ([ "${RUNNER_OS}" == "macOS" ] && [ "$arch" == "universal2" ]); then
+            # cffi is a dep of cryptography and doesn't ship
+            # a universal2 wheel so we must build one ourself :-/
+            export CFLAGS="-arch x86_64 -arch arm64"
+            export ARCHFLAGS="-arch x86_64 -arch arm64"
             "${PYTHON}" -m pip install --upgrade --force-reinstall --no-binary :all: \
                               --no-cache-dir --no-deps --use-pep517 \
                               --use-feature=no-binary-enable-wheel-cache \
                               cffi 
             echo "before cryptography..."
             "${PYTHON}" -m pip list
+            # cryptography has a universal2 wheel but getting it installed
+            # on x86-64 MacOS is a royal pain in the keester.
             "${PYTHON}" -m pip download --only-binary :all: \
-                                        --dest . \
-                                        --no-cache \
-                                        --no-deps \
-                                        --platform ${CRYPT_PLATFORM} \
-                                        --verbose \
-                                       cryptography
-            "${PYTHON}" -m pip install --force-reinstall --no-deps --verbose cryptography*.whl
+                                          --dest . \
+                                          --no-cache \
+                                          --no-deps \
+                                          --platform macosx_10_15_universal2 \
+                                          cryptography
+            "${PYTHON}" -m pip install --force-reinstall --no-deps cryptography*.whl
             echo "after cryptography..."
             "${PYTHON}" -m pip list
             "${PYTHON}" -m pip install --upgrade --no-binary :all: -r requirements.txt
@@ -468,16 +450,8 @@ jobs:
         run: |
              export gampath="./dist/gamadv-xtd3"
              mkdir -p -v "${gampath}"
-             export gamspec="gam.spec"
              if [[ "${RUNNER_OS}" == "macOS" ]]; then
                export gampath=$($PYTHON -c "import os; print(os.path.realpath('$gampath'))")
-               if [[ "${arch}" == "arm64" ]]; then
-                 export gamspec="gamarm64.spec"
-               elif [[ "${arch}" == "x86_64" ]]; then
-                 export gamspec="gamx86_64.spec"
-               else
-                 export gamspec="gamuniversal2.spec"
-               fi
              elif [[ "${RUNNER_OS}" == "Windows" ]]; then
                # Work around issue where PyInstaller picks up python3.dll from other Python versions
                # https://github.com/pyinstaller/pyinstaller/issues/7102
@@ -489,7 +463,12 @@ jobs:
              echo "gampath=${gampath}" >> $GITHUB_ENV
              echo "gam=${gam}" >> $GITHUB_ENV
              echo -e "GAM: ${gam}\nGAMPATH: ${gampath}"
-             "${PYTHON}" -m PyInstaller --clean --noconfirm --distpath="${gampath}" "${gamspec}"
+             # TEMP force everything back to one file.
+             export PYINSTALLER_BUILD_ONEFILE="yes"
+             export distpath="./dist/gam"
+             export gampath="${distpath}"
+             "${PYTHON}" -m PyInstaller --clean --noconfirm --distpath="${gampath}" gam.spec
+             cat build/gam/warn-gam.txt
 
       - name: Copy extra package files
         if: matrix.goal == 'build'
@@ -504,13 +483,9 @@ jobs:
 
       - name: Basic Tests all jobs
         run: |
-          if [[ "${RUNNER_OS}" != "macOS" ]]; then
-            $gam version extended nooffseterror
-            export GAMVERSION=$($gam version simple)
-          elif [[ "${arch}" != "arm64" ]]; then
-            $gam version extended nooffseterror
-            export GAMVERSION=$($gam version simple)
-          fi
+          $PYTHON -m unittest discover --start-directory ./ --pattern "*_test.py" --buffer || if [ $? != 5 ]; then exit $?; fi # exit 5 is no tests
+          $gam version extended nooffseterror
+          export GAMVERSION=$($gam version simple)
           echo "GAM Version ${GAMVERSION}"
           echo "GAMVERSION=${GAMVERSION}" >> $GITHUB_ENV
 
@@ -572,24 +547,22 @@ jobs:
       - name: Basic Tests build jobs only
         if: matrix.goal != 'test' && steps.cache-python-ssl.outputs.cache-hit != 'true'
         run: |
-          if [[ "${RUNNER_OS}" != "macOS" ]]; then
-            export voutput=$($gam version extended nooffseterror)
-            export python_line=$(echo -e "${voutput}" | grep "Python ")
-            export python_arr=($python_line)
-            export this_python=${python_arr[1]}
-            if [[ "${this_python}" != "${COMPILED_PYTHON_VERSION}" ]]; then
-              echo "ERROR: Tried to compile Python ${COMPILED_PYTHON_VERSION} but ended up with ${this_python}"
-              exit 1
-            fi
-            export openssl_line=$(echo -e "${voutput}" | grep "OpenSSL ")
-            export openssl_arr=($openssl_line)
-            export this_openssl="${openssl_arr[1]}"
-            if [[ "${this_openssl}" != "${COMPILED_OPENSSL_VERSION}" ]]; then
-              echo "ERROR: Tried to compile OpenSSL ${COMPILED_OPENSSL_VERSION} but ended up with ${this_openssl}"
-              exit 1
-            fi
-            echo "We successfully compiled Python ${this_python} and OpenSSL ${this_openssl}"
+          export voutput=$($gam version extended nooffseterror)
+          export python_line=$(echo -e "${voutput}" | grep "Python ")
+          export python_arr=($python_line)
+          export this_python=${python_arr[1]}
+          if [[ "${this_python}" != "${COMPILED_PYTHON_VERSION}" ]]; then
+            echo "ERROR: Tried to compile Python ${COMPILED_PYTHON_VERSION} but ended up with ${this_python}"
+            exit 1
           fi
+          export openssl_line=$(echo -e "${voutput}" | grep "OpenSSL ")
+          export openssl_arr=($openssl_line)
+          export this_openssl="${openssl_arr[1]}"
+          if [[ "${this_openssl}" != "${COMPILED_OPENSSL_VERSION}" ]]; then
+            echo "ERROR: Tried to compile OpenSSL ${COMPILED_OPENSSL_VERSION} but ended up with ${this_openssl}"
+            exit 1
+          fi
+          echo "We successfully compiled Python ${this_python} and OpenSSL ${this_openssl}"
 
       - name: Archive production artifacts Linux/MacOS
         uses: actions/upload-artifact@v3
@@ -612,7 +585,12 @@ jobs:
         if: matrix.goal == 'build' && steps.cache-python-ssl.outputs.cache-hit != 'true'
         working-directory: ${{ github.workspace }}
         run: |
-          tar cJvvf bin.tar.xz bin/
+          if [[ "${RUNNER_OS}" == "Windows" ]]; then
+            tar_folders="src/cpython/ bin/ssl"
+          else
+            tar_folders="bin/"
+          fi
+          tar cJvvf cache.tar.xz "$tar_folders"
   
   publish-winget:
     runs-on: windows-2022
